name: Build and Test Gem 

on:
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        ruby-version: ['3']

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}

    - name: Install dependencies
      run: bundle install

    - name: Compile native extension
      run: bundle exec rake compile

    - name: Build the Gem
      run: gem build fast_xirr.gemspec

    - name: Install the Gem
      run: gem install ./fast_xirr-*.gem --no-document

    - name: Run tests
      run: rake test
